---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  
  tasks:

  - name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false
  
  - name: Get list of hosts for the root user.
    command: mysql -NBe
      "SELECT Host
      FROM mysql.user
      WHERE User = '{{ mysql_root_username }}'
      ORDER BY (Host='localhost') ASC"
    register: mysql_root_hosts
    changed_when: false
    check_mode: false
    when: mysql_install_packages | bool or mysql_root_password_update
