---
- hosts: all
  become: yes
  
  tasks:

  - name: Create new databases using a list
    mysql_db:
      name: 
        - db_1
        - db_2
      state: present

  - name: Dump multiple databases
    mysql_db:
      state: dump
      name:
        - db_1
        - db_2
    target: /tmp/dump.sql

